### ISSUE TITLE
Cannot connect to host celestrak.com:443

### ISSUE THREAD

**Issue by benb0jangles** [RedBalloonShenanigans/antenny#89]
on MacOS 10.12.6

I'm getting:

ClientConnectorCertificateError: Cannot connect to host celestrak.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]

Any reason?

**Comment by benb0jangles** [comment]
I get this error when I command, any ideas?

perhaps because i'm using python 3.8?

track starlink-1225:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 916, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/benji/antenny/nyansat/host/shell/__main__.py", line 463, in <module>
    sys.exit(main())
  File "/Users/benji/antenny/nyansat/host/shell/__main__.py", line 457, in main
    nyanshell.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/benji/antenny/nyansat/host/shell/errors.py", line 28, in wrapper
    func(*args, **kwargs)
  File "/Users/benji/antenny/nyansat/host/shell/__main__.py", line 326, in do_track
    self.client.track(sat_name)
  File "/Users/benji/antenny/nyansat/host/shell/errors.py", line 13, in wrapper
    func(*args, **kwargs)
  File "/Users/benji/antenny/nyansat/host/shell/antenny_client.py", line 135, in track
    asyncio.run(self._start_track(sat_name, (latitude, longitude)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/benji/antenny/nyansat/host/shell/antenny_client.py", line 337, in _start_track
    tle_data_encoded = await SatelliteScraper.load_tle()
  File "/Users/benji/antenny/nyansat/host/satdata_client.py", line 28, in load_tle
    return await scraper.get_tle_lines()
  File "/Users/benji/antenny/nyansat/host/satdata_client.py", line 19, in get_tle_lines
    await self.get_tle_file()
  File "/Users/benji/antenny/nyansat/host/satdata_client.py", line 15, in get_tle_file
    async with session.get(source) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/client.py", line 963, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/client.py", line 442, in _request
    conn = await self._connector.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 507, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 838, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 983, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 960, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 918, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host celestrak.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]

```

**Comment by yuanzhewu** [comment]
This could be a issue of how OS X handle certificate for python3.8.

**Comment by benb0jangles** [comment]
MacOS Sierra has issues with ssl certain ssl certificates? >
so
Install Certificates.command

https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify
