### ISSUE TITLE
Issue in upload calibration data

### ISSUE THREAD

**Issue by kernelpanic-bf** [RedBalloonShenanigans/antenny#92]
When trying to use the command `upload_calibration` it seems to error out on my system. (See error below)

I think I found the mistake in the following line:
https://github.com/RedBalloonShenanigans/antenny/blob/9e33c643516e24bf92bb2269c7add5c64490afd9/nyansat/station/imu/imu_bno055.py#L175
`for register_name, register_address in self.CALIBRATION_REGISTERS:`
It needs to be changed to:
`for register_name, register_address in self.CALIBRATION_REGISTERS.items():`

```Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kernelpanic/Projects/satelliteFun-20200817/4-Files/micropython/antenny2/antenny/nyansat/host/shell/__main__.py", line 463, in <module>
    sys.exit(main())
  File "/home/kernelpanic/Projects/satelliteFun-20200817/4-Files/micropython/antenny2/antenny/nyansat/host/shell/__main__.py", line 457, in main
    nyanshell.cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/kernelpanic/Projects/satelliteFun-20200817/4-Files/micropython/antenny2/antenny/nyansat/host/shell/__main__.py", line 223, in do_upload_calibration
    self.client.upload_calibration()
  File "/home/kernelpanic/Projects/satelliteFun-20200817/4-Files/micropython/antenny2/antenny/nyansat/host/shell/errors.py", line 13, in wrapper
    func(*args, **kwargs)
  File "/home/kernelpanic/Projects/satelliteFun-20200817/4-Files/micropython/antenny2/antenny/nyansat/host/shell/antenny_client.py", line 153, in upload_calibration
    status = self.invoker.imu_upload_calibration_profile()
  File "/home/kernelpanic/Projects/satelliteFun-20200817/4-Files/micropython/antenny2/antenny/nyansat/host/shell/command_invoker.py", line 142, in imu_upload_calibration_profile
    return self.eval_string_expr("api.imu.upload_calibration_profile('calibration.json')")
  File "/home/kernelpanic/Projects/satelliteFun-20200817/4-Files/micropython/antenny2/antenny/nyansat/host/shell/nyan_pyboard.py", line 14, in eval_string_expr
    ret = self.exec_("print(eval({}))".format(command))
  File "/usr/local/lib/python3.8/dist-packages/mpfshell-0.9.1-py3.8.egg/mp/pyboard.py", line 156, in exec_
    raise PyboardError("exception", ret, ret_err)
mp.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\n  File "<string>", line 1, in <module>\r\n  File "imu/imu_bno055.py", line 171, in upload_calibration_profile\r\n  File "imu/imu_bno055.py", line 175, in _set_calibration_profile\r\nValueError: too many values to unpack (expected 2)\r\n')
```

**Comment by benb0jangles** [comment]
upload calibration? Just run calibrate in shell and at the end it will save?
