### ISSUE TITLE
track starlink-1743

### ISSUE THREAD

**Issue by benb0jangles** [RedBalloonShenanigans/antenny#95]
command:
track starlink-1743

result:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/benji/antenny/nyansat/host/shell/__main__.py", line 463, in <module>
    sys.exit(main())
  File "/home/benji/antenny/nyansat/host/shell/__main__.py", line 457, in main
    nyanshell.cmdloop()
  File "/usr/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/benji/antenny/nyansat/host/shell/errors.py", line 28, in wrapper
    func(*args, **kwargs)
  File "/home/benji/antenny/nyansat/host/shell/__main__.py", line 326, in do_track
    self.client.track(sat_name)
  File "/home/benji/antenny/nyansat/host/shell/errors.py", line 13, in wrapper
    func(*args, **kwargs)
  File "/home/benji/antenny/nyansat/host/shell/antenny_client.py", line 135, in track
    asyncio.run(self._start_track(sat_name, (latitude, longitude)))
AttributeError: module 'asyncio' has no attribute 'run'

any ideas?

Setup:
Jetson Nano arm64
Ubuntu 18.4.5
Python 3.6.9

**Comment by benb0jangles** [comment]
AttributeError: module 'asyncio' has no attribute 'run'

asyncio.run is new in Python 3.7 or above. jetson is using python 3.6.9
https://github.com/omnilib/aiomultiprocess/issues/21#issuecomment-492439725
