### ISSUE TITLE
ImportError: cannot import name 'WebSocketConnectionClosedException' from 'websocket'

### ISSUE THREAD

**Issue by benb0jangles** [RedBalloonShenanigans/antenny#98]
Help? Or Silence?

Running command:
`python3 -m nyansat.host.shell
`
Give error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/benji2/antenny/nyansat/host/shell/__main__.py", line 6, in <module>
    from websocket import WebSocketConnectionClosedException
ImportError: cannot import name 'WebSocketConnectionClosedException' from 'websocket' (/usr/local/lib/python3.9/dist-packages/websocket/__init__.py)

```

**Comment by abansal567** [comment]
Hey, I think you may have resolved this issue by now and I am kinda stuck at the same thing to install nyansat on ESP32. Can you direct me if you have resolved this already?

**Comment by dannyp303** [comment]
Hello, we have made many updates to the `station` code to make it more usable/reliable/understandable. That being said, the `host` code is now under construction. On a related note, I highly suggest using the python interpreter as described in the updated README to operate the device as it is still under development and the host shell hides/does not have acces to a lot of information and errors.
